Ok, I was joking. bash is better for bin/setup

diff --git a/templates/bin_setup b/templates/bin_setup
--- a/templates/bin_setup
+++ b/templates/bin_setup
@@ -1,34 +1,22 @@
-#!/usr/bin/env ruby
-require 'fileutils'
-include FileUtils
+#!/bin/sh
 
-APP_ROOT = File.expand_path('..', __dir__)
+# Set up Rails app. Run this script immediately after cloning the codebase.
 
-def system!(*args)
-  system(*args) || abort("\n== Command #{args} failed ==")
-end
+# Exit if any subcommand fails
+set -e
 
-chdir APP_ROOT do
-  puts '== Installing dependencies =='
-  system! 'gem install bundler --conservative'
-  system('bundle check') || system!('bundle install')
+echo '== Installing dependencies =='
+gem install bundler --conservative
+bundle check || bundle install
+bin/yarn
 
-  system('bin/yarn')
+echo "\n== Copying sample files =="
+if [ ! -f .env.local ]; then
+  cp .env .env.local
+fi
 
-  puts "\n== Copying sample files =="
-  unless File.exist?('.env.local')
-    cp '.env', '.env.local'
-  end
+echo "\n== Preparing database and seeds =="
+bin/rails dev:prime
 
-  puts "\n== Preparing database and seeds =="
-  system! 'bin/rake dev:prime'
-
-  puts "\n== Removing old logs and tempfiles =="
-  system! 'bin/rails log:clear tmp:clear'
-
-  puts "\n== Restarting application server =="
-  system! 'bin/rails restart'
-
-  puts "\n== Activating overcommit =="
-  system! 'bin/overcommit --install'
-end
+echo "\n== Activating overcommit =="
+bin/overcommit --install
